### Sparse Matrix

In [1]:
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
 [0, 1],
 [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [3]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [4]:
print(matrix_sparse)# returns the non-zero elements with their indices

  (1, 1)	1
  (2, 0)	3


#### Selecting elements

In [5]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Select third element of vector
vector[2]
3
# Select second row, second column
matrix[1,1]

5

### Use NumPy’s vectorize:
- Load library

- Create matrix

- Create function that adds 100 to something

- Create vectorized function

- Apply function to all elements in matrix


In [7]:
import numpy as np
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
add_100 = lambda i: i + 100
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [8]:
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
np.mean(matrix, axis = 0)# mean per column

array([4., 5., 6.])

In [9]:
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
np.mean(matrix, axis = 1)

array([2., 5., 8.])

In [10]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [12]:
a = matrix.reshape(-1, 1)

In [14]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [1]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Create matrix
matrix = np.array([[1, 1, 1],
 [1, 1, 10],
 [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [8]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return determinant of matrix
print(np.linalg.det(matrix))

# Return diagonal elements
print(matrix.diagonal())

# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

# Return trace- This is the sum of all diagonal elements
#it proves results in linear algebra
matrix.trace()

0.0
[1 4 9]
[2 6]
[2 8]


14

In [13]:
# Create matrix
matrix = np.array([[1, -1, 3],
 [1, 1, 6],
 [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print('Eigenvalues\n',eigenvalues)

print('Eigenvectors\n',eigenvectors)

Eigenvalues
 [13.55075847  0.74003145 -3.29078992]
Eigenvectors
 [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [14]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [19]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1, 1],
 [1, 1, 1],
 [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
 [1, 3, 1],
 [1, 3, 8]])
# Add two matrices
print("Sum of two matrices is\n",np.add(matrix_a, matrix_b))

# Subtract two matrices
print("Difference of two matrices is\n",np.subtract(matrix_a, matrix_b))

# dot product
print("The dot product is\n",np.dot(matrix_a,matrix_b))

#Element-wise
print("Element-wise product is\n",matrix_a*matrix_b)

Sum of two matrices is
 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
Difference of two matrices is
 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
The dot product is
 [[ 3  9 10]
 [ 3  9 10]
 [ 4 12 18]]
Element-wise product is
 [[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]]


In [22]:
# Create matrix
matrix = np.array([[1, 4],
 [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [26]:
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
print("Random floats vector\n",np.random.random(3))

# Generate three random integers between 1 and 10
print("Random integers vector\n",np.random.randint(0, 11, 3))

# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
print("Random numbers from normal vector\n",np.random.normal(0.0, 1.0, 3))

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
print("Random numbers from logistic vector\n",np.random.logistic(0.0, 1.0, 3))

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print("Random numbers between 1.0 and 2.0 vector\n",np.random.uniform(1.0, 2.0, 3))

Random floats vector
 [0.5488135  0.71518937 0.60276338]
Random integers vector
 [3 7 9]
Random numbers from normal vector
 [-1.42232584  1.52006949 -0.29139398]
Random numbers from logistic vector
 [-0.98118713 -0.08939902  1.46416405]
Random numbers between 1.0 and 2.0 vector
 [1.47997717 1.3927848  1.83607876]
